### ISSUE TITLE
Explorer panel cutting off parts of details view

### ISSUE THREAD

**Issue by ben401rs** [sakasakiking/FusionX#10]
It works correctly before an update makes the extrametadata video loader or maybe something else caused it to be too big and cut off when explorer panel is open

![image](https://github.com/user-attachments/assets/1b077912-13fb-462e-9c95-ec7b1aa00ad0)

**Comment by sakasakiking** [comment]
Yea, I know it. It has a min-width that cause the issue. BTW, what's your display resolution?

**Comment by kyotocafe** [comment]
This is similar to what is happening to me now since the new version was released. 

I am attaching two screenshots with how it was being displayed before and how it is displayed now, my resolution is 2560 × 1440 

<img width="960" alt="now" src="https://github.com/user-attachments/assets/3bb6b659-7569-4826-8ab4-bef51f90fd10">
<img width="960" alt="before" src="https://github.com/user-attachments/assets/13aaf65e-34d6-488a-bfe3-35d8aaf5609c">

Amazing theme, it has become my favourite by far. Thank you for all the effort you are putting into this.

**Comment by kyotocafe** [comment]
I've just found out that editing the layout and details view parameters, it can make it look quite good

![edited layout](https://github.com/user-attachments/assets/8d281b35-db12-4a1c-894c-fe120a92a0a9)

Detail view parameters
![details view parameters](https://github.com/user-attachments/assets/0b5ab7a4-a985-4ed3-bef5-10b473758e95)

Layout parameters
![layout parameters](https://github.com/user-attachments/assets/878175b2-c1df-429e-aada-e1f24ca7b098)

**Comment by kyotocafe** [comment]
Though I wonder what is this overview thing that is empty

![overview](https://github.com/user-attachments/assets/16d274fc-176b-46d9-a368-abdd8cf6bba9)

**Comment by sakasakiking** [comment]
> Though I wonder what is this overview thing that is empty
> 
> ![overview](https://private-user-images.githubusercontent.com/714680/383130247-16d274fc-176b-46d9-a368-abdd8cf6bba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDc0MjIsIm5iZiI6MTczMDgwNzEyMiwicGF0aCI6Ii83MTQ2ODAvMzgzMTMwMjQ3LTE2ZDI3NGZjLTE3NmItNDZkOS1hMzY4LWFiZGQ4Y2Y2YmJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMTQ1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzA1NDVhMGJkYWRhNzM1ZGM2M2VkY2MzYWVjMDA4Njk5MTIzYmRhNDM2NmE3MDYyZTRlZjEwMDFlZmMyYzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.W6FXwHQHYDbdX4sJJhTCUgsQ9pgR_Ld43O66rG2DS0c)

Thank you for loving it. It gonna keep improving.

**Comment by sakasakiking** [comment]
I’m looking into it. And all the issues will be fixed and release out in next version.

**Comment by sakasakiking** [comment]
Now in DetailOverview, the width of content is set to a appropriate size that could fit most resolution.
For the GridOverView, don't set the width of "Grid view detail" less than 600.
