### ISSUE TITLE
Add separate overview tab for Notes

### ISSUE THREAD

**Issue by adrian5683** [sakasakiking/FusionX#11]
Thank you for converting Details to Grid View, donation incoming! It looks awesome.

Would it also be possible to add Notes as a separate tab, next to the Overview section? Right now they appear at the top of any game description in the Overview section. Thanks for considering.

**Comment by sakasakiking** [comment]
Thanks for the donation. Just curious to know what you do with the notes? I actually don't write most of the time.

**Comment by adrian5683** [comment]
I play a lot of old school RPGs, so for something like Might and Magic I-V I use it as a journal to write down quest markers and such. For a lot of old games it's mainly tracking progression since I rarely spend more than a month with the same game.

**Comment by sakasakiking** [comment]
Yea, got it. I like retro games, too. BTW, I like M&M VI, that's my first M&M game to play with. Heroes of M&M is a good series, too.

**Comment by sakasakiking** [comment]
Done. Will release in v1.2.
