### ISSUE TITLE
Play button "feels" missaligned

### ISSUE THREAD

**Issue by rumpff** [sakasakiking/FusionX#16]
The play/running text feels missaligned to me because of the settings section, i think it would look better if the label was aligned to the button excluding the settings part, instead of being aligned to the entire button.

here is a mockup to show the difference 
<img width="600" alt="buttons mockup" src="https://github.com/user-attachments/assets/94507ed2-4de1-4b99-b30e-c5af02313d45">

**Comment by sakasakiking** [comment]
Yeah, I got it. I was also struggling on it for a long time actually. Thank you for your feedback,  let me look into it.

**Comment by sakasakiking** [comment]
Fixed and close this issue.
