### ISSUE TITLE
1.3版本的extra metadata loader的logo显示异常

### ISSUE THREAD

**Issue by EdenGoat** [sakasakiking/FusionX#17]
1.1版本的图标错位，但是大小显示是正常的，更新成1.2后图标就变得小小一个，1.3问题还是延续了
![1](https://github.com/user-attachments/assets/3a040018-3b9f-4d3e-ae54-e8676e979047)
这是1.3版本的

![WeChat截图_20241211191625](https://github.com/user-attachments/assets/8c832814-b3e4-4034-a87f-9fc084f0089a)
这是1.1版本的

**Comment by sakasakiking** [comment]
Hi，多谢反馈。你指的图标是指最下边的游玩时间处的图标么？还是指单独的那个“旗帜”图标？

**Comment by EdenGoat** [comment]
> Hi，多谢反馈。你指的图标是指最下边的游玩时间处的图标么？还是指单独的那个「旗帜」图标？

是左上角的游戏logo，通过extra metadata loader引入的。谢谢大佬的制作，希望可以修复这个问题！
![1](https://github.com/user-attachments/assets/859a68e1-ea4b-4c66-a4b4-eaaf0d42e06c)
![2](https://github.com/user-attachments/assets/17d3313c-96a4-461b-8d6f-5153046d6529)

**Comment by sakasakiking** [comment]
OK。这个地方你需要到设置->详细视图，设置一个你想留给LOGO的高度，当然这里是一个我没有考虑进去的问题。多谢反馈。
![image](https://github.com/user-attachments/assets/b1f665df-a844-49ee-acdd-39a2ab73f101)

**Comment by EdenGoat** [comment]
这个办法对于竖版或是正方形的图标有效，但是横板的图标就会空出一大块，只不过问题不大，如果可以的话希望下版本可以修复，谢谢您！
![3](https://github.com/user-attachments/assets/325d1802-f6ff-41b6-9f0f-87887b53d0ce)

**Comment by sakasakiking** [comment]
嗯~图标下空出的一大片，是根据你自己的口味设定的，一是留给logo的尺寸，二是留给背景图片的露出。这要根据每个人的喜好，并不能说明这就是一个BUG。因此，这个体验的部分会以合适的方式来推进，并不会在某一版本内一下子“修复”。

**Comment by EdenGoat** [comment]
老版本不会这样的，我记得当时简介页面你也放了一张黑神话页面的图，老版本评分、日期、tag那些直接就会在logo下面的。目前的情况是假如那个竖直间距给少了，竖版的logo就会被压缩，给多了很棒下方又会空出来。

**Comment by sakasakiking** [comment]
嗯~当时的设计是把settings间距作为最小的实际间距，实际间距是logo本身大小。这样会产生其他的问题。我建议是调整竖直间距，这样比较简单。然后下一版会把logo竖直居中，这样会更美观一点。

**Comment by EdenGoat** [comment]
好的，谢谢
