### ISSUE TITLE
TopPanelItem fixed width (=32) restriction

### ISSUE THREAD

**Issue by gittromney** [sakasakiking/FusionX#3]
Hi, I'm working on style tweaking the NowPlaying game cacher plugin to play nice with FusionX.  I love the look of the FusionX theme btw, but it's also the only Playnite theme I've worked with that fixes/limits the width of a plugin's TopPanelItem.  The NowPlaying plugin displays (or tries to display) a width=200-ish progress bar as a TopPanelItem during game cache activity.  As you can imagine that isn't working well with FusionX, at the moment.

My Request: consider changing Width=32 to MinWidth=32 in your TopPanelItem style, assuming that doesn't break any of your other control stylings.

Thanks in advance,
--gittromney

**Comment by gittromney** [comment]
Oh, and one more request (while I'm at it):

Also please consider changing the HoverBg/SelectedBg from Elispes to radiused Rectangles (in the ball-park of RadiusX/Y=15-ish),
which imo would handle the wide cases (e.g. NowPlaying progress bar) much better than an elispse.

--g

**Comment by sakasakiking** [comment]
Thank you for your advice. I'll get these in consideration.

**Comment by sakasakiking** [comment]
Fixed. Will release soon.

**Comment by gittromney** [comment]
works great. thx --g
