### ISSUE TITLE
Add UI Style Similar to Screenshot (Anime/Japanese Aesthetic + Win11 Mica Effect)

### ISSUE THREAD

**Issue by FENBIANKELI** [sakasakiking/FusionX#4]
Hello! I love the FusionX theme, and I was wondering if it would be possible to implement a UI style similar to the one in the screenshot I’ve attached. It has a beautiful anime/Japanese aesthetic with a Windows 11 mica effect, and I think it would be a great addition for ACG culture fans.

Would it be possible to make this kind of design happen in FusionX?

Thank you so much for considering it!
![Snipaste_2024-10-08_02-28-51](https://github.com/user-attachments/assets/cafcdfb6-bc63-4e5e-8993-69e0dc695220)
![Snipaste_2024-10-08_02-29-03](https://github.com/user-attachments/assets/fa10aa65-eb1e-4ba4-b4d1-64427093c0fa)
![Snipaste_2024-10-08_02-29-23](https://github.com/user-attachments/assets/2df59dec-6b78-452c-8253-3bbe2c06d11c)
![Snipaste_2024-10-08_02-30-47](https://github.com/user-attachments/assets/35b0c032-d5d7-498f-8ab2-b4ec2546e0f1)
![Snipaste_2024-10-08_02-31-18](https://github.com/user-attachments/assets/4655ecf3-e021-40ae-8bd9-7147a99d8b22)
![Snipaste_2024-10-08_02-32-18](https://github.com/user-attachments/assets/27d54545-6cc1-4bd6-aaf8-d28db531ea3d)

**Comment by sakasakiking** [comment]
Thank you for using it. Do you mean the blurred glass effect? Acctually, I like the effect and used it in my design concept, but I found, it needs to edit the playnite C# file which means I can't do this by only editing the xaml file (Theme file) . Maybe there's way to make the effect happen, but I don't know it.
