### ISSUE TITLE
Option to disable favorite icon on game covers

### ISSUE THREAD

**Issue by Allebale** [sakasakiking/FusionX#5]
Hi, thanks for making a wonderfull theme. I would like to disable the star logos on all game covers. Im pretty sure that it was disabled before but i tried to disable it in the various xaml files but i could not find or didn't understand how to disable it.

Could you please help me disable it in the xaml files or make an option to disable it.

![disablestars](https://github.com/user-attachments/assets/b95405b3-1833-40b7-b5ae-7372cca83e6e)
As you can see i have disabled other stuff as well since i have an oled tv as i try to minimize burn-in on stuff.

Thanks!

**Comment by Allebale** [comment]
I fixed it myself.

For anyone else wondering, open \AppData\Roaming\Playnite\Themes\Desktop\FusionX_54244ec8-29ec-418e-bce7-415250c8d67b\DerivedStyles\GridViewItemTemplate.xaml

and change: <Setter Property="Visibility" Value="Visible" /> to <Setter Property="Visibility" Value="Hidden" />

**Comment by Allebale** [comment]
I fixed it myself.

For anyone else wondering, open AppData\Roaming\Playnite\Themes\Desktop\FusionX_54244ec8-29ec-418e-bce7-415250c8d67b\DerivedStyles\GridViewItemTemplate.xaml

and edit line 50, change Visible to Hidden

**Comment by sakasakiking** [comment]
Thanks man
