### ISSUE TITLE
Add Details to Grid View Converter support

### ISSUE THREAD

**Issue by adrian5683** [sakasakiking/FusionX#6]
Hi, absolutely love this theme! I mostly use grid view and would love it if it had support for Details to Grid View Converter. Thanks for considering.

**Comment by sakasakiking** [comment]
Yea, got it considered. Just wondering would most users like to use it like this?

**Comment by adrian5683** [comment]
Can't speak for others but I would use grid view + converter with the explorer panel open, and mess with the Layout settings to basically achieve the UI that GOG Galaxy 2 has. I used Neon theme to get this effect in the past.

**Comment by sakasakiking** [comment]
OK, get it done. But I did not make it happen via the plugin... I just wrote the code within the xaml file directly, so roughly~
