### ISSUE TITLE
HowLongToBeat not showing up

### ISSUE THREAD

**Issue by ShakedGold** [sakasakiking/FusionX#7]
This theme looks great!
however I can't seem to see the HowLongToBeat section
I have it installed and it works on other themes
![image](https://github.com/user-attachments/assets/7edfdb26-80a6-43c0-9876-cdb54d7aae28)
Helium for example:
![image](https://github.com/user-attachments/assets/8ec52aec-3428-42de-b67c-2b87e68a99ca)

**Comment by sakasakiking** [comment]
It will show up in next release. Thanks for using.
