### ISSUE TITLE
Details view extrametadata logo is all over the place

### ISSUE THREAD

**Issue by ben401rs** [sakasakiking/FusionX#8]
As the title said, it sometimes look too big, positioned weirdly or looks odd

![Cuplikan layar 2024-11-02 164403](https://github.com/user-attachments/assets/64c918ee-c599-42c0-90a6-5fae4587d879)

**Comment by sakasakiking** [comment]
Sorry for that. But you might know the size of logo is based on its settings
![image](https://github.com/user-attachments/assets/11488136-ef54-409a-b40b-9ad8f351c253)

**Comment by sakasakiking** [comment]
Got it. Thank you for your advice.

**Comment by sakasakiking** [comment]
The logo is set to a appropriate size and will be auto scaled with the window.
