### ISSUE TITLE
Add cover art platform logo for the cover art and grid view

### ISSUE THREAD

**Issue by ben401rs** [sakasakiking/FusionX#9]
Looks cool if implemented, Nova X theme has it and looks like this

![image](https://github.com/user-attachments/assets/4e2fe76d-7699-449e-8aef-6b435b10ffe7)

![image](https://github.com/user-attachments/assets/14b7e040-7cb1-454f-86d9-536d13d2d85c)

**Comment by sakasakiking** [comment]
Do you mean the platform logo only?

**Comment by sakasakiking** [comment]
Done
